In [27]:
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt


In [28]:
!pip install opencv-python
!pip install matplotlib

# Membaca Gambar

In [29]:
img = cv.imread("tengkorak.jpg")

In [30]:
cv.imshow('Image', img)
cv.waitKey(0)
cv.destroyAllWindows()

In [31]:
print(img.shape)

(517, 612, 3)


# Split RGB Image

In [32]:
b= img[:,:,0]
g= img[:,:,1]
r= img[:,:,2]

# RGB to Greyscale with OpenCV

In [33]:
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

In [34]:
cv.imshow('Gray', gray)
cv.waitKey(0)
cv.destroyAllWindows()

In [35]:
print(gray.shape)

(517, 612)


# Mengubah pixel 

In [36]:
panjang = len(img)
lebar = len(img[0])

img_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        img_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]

        img_gray = img_gray.astype(np.uint8)

In [37]:
cv.imshow("Abu", img_gray)
cv.waitKey(0)
cv.destroyAllWindows()

In [38]:
print(img_gray)

[[ 0  0  0 ...  3  3  3]
 [ 0  0  0 ...  3  3  3]
 [ 0  0  0 ...  3  3  3]
 ...
 [ 1  1  1 ...  3  7 14]
 [ 1  1  1 ...  3  7 14]
 [ 1  1  1 ...  3  7 14]]


# Grayscale to Binary with OpenCV

In [39]:
(thresh, binary) = cv.threshold(gray, 128, 225, cv.THRESH_BINARY | cv.THRESH_OTSU)

In [40]:
cv.imshow('Gray', binary)
cv.waitKey(0)
cv.destroyAllWindows()

In [41]:
print(binary.shape)

(517, 612)
